### ISSUE TITLE
Add file name parsing logic

### ISSUE THREAD

**Issue by uranusjr** [pypa/packaging#136]
Related to pypa/pip#5800. No matter whether the repository fetcher is added or not, I feel it would be very beneficial if there is a well-tested way to parse entries in a simple API page. Something like

```python
>>> Distribution.from_filename('zope.interface-4.5.0.tar.gz', name='zope.interface')
SourceDistribution(name='zope.interface', version='4.5.0', filename='zope.interface-4.5.0.tar.gz')
>>> Distribution.from_filename('zope.interface-4.5.0-cp36-cp36m-win_amd64.whl', name='zope.interface')
WheelDistribution(name='zope.interface', version='4.5.0', filename='zope.interface-4.5.0-cp36-cp36m-win_amd64.whl')
```

**Comment by cjerdonek** [comment]
This older pip issue seems related: https://github.com/pypa/pip/issues/1689

**Comment by uranusjr** [comment]
For completeness, here are some existing implementations:

* distlib: https://bitbucket.org/vinay.sajip/distlib/src/a586fab287abc1f34d1d5e251ef20ae19d1ad51e/distlib/util.py#cl-521
* pip: https://github.com/pypa/pip/blob/18.1/src/pip/_internal/index.py#L796
* Proposed rewrite for pip (currently WIP): pypa/pip#5875

**Comment by uranusjr** [comment]
I put together a POC: https://github.com/uranusjr/packaging-dists

**Comment by brettcannon** [comment]
Do we need the sdist v0 PEP to land to get sdist filename parsing standardized?

**Comment by dstufft** [comment]
One could argue it's roughly the same as the "legacy version" support in ``packaging.version``.  I would say if we're adding support for parsing wheels, it would make sense to add support for sdists regardless of a PEP for them... but we may not *want* to because currently parsing a sdist is ambiguous, which means that a parsing API for them would need a different "shape" than I think would be ideal?

**Comment by uranusjr** [comment]
I think we should provide *some* kind of logic to parse legacy sdists in packaging. Tool developers are stuck dealing with them until the end of time. People will need to hand-roll something if we don’t provide them a solution, and hit all the same edge cases pip did all over again until they eventually come up with basically what pip does right now. So it’s better if we just do that for them. We can try to communicate the fact that the logic is not always bullet-proof (name the function `guess_sdist_name` or something, for example).

**Comment by pradyunsg** [comment]
> Do we need the sdist v0 PEP to land to get sdist filename parsing standardized?

We should before we merge it perhaps?

I don't think we *need* de-jure standardization to start working on this, since the de-facto standardization (i.e. what pip does) is stable enough IMO. I'm on board for hashing out the PR, prior to accepting/writing the corresponding PEPs even -- since the process of writing the corresponding PR can serve as a good learning opportunity. :)

> We can try to communicate the fact that the logic is not always bullet-proof

Definitely. I feel like the "legacy" nature of some of our functions naming does this pretty well, but not a 100% about -- as Donald put it -- what the "shape" should be.

**Comment by brettcannon** [comment]
I'm totally onboard if we can communicate that legacy sdists are a best-effort parse. Otherwise I expect this will inform us on how much of a pain it might be to try and support both standardized and old sdist formats if we don't change the file extension.

Plus I was planning to write this code someday anyway (hence why I got involved in the sdist standardization work), so if @uranusjr beats me to it then that's fine by me. 😁

**Comment by pradyunsg** [comment]
This is done now.

**Comment by pradyunsg** [comment]
https://packaging.pypa.io/en/latest/changelog.html#id5
