### ISSUE TITLE
Add metadata validation

### ISSUE THREAD

**Issue by bittner** [pypa/packaging#147]
I'm trying to help fix the issue of broken package descriptions on PyPI (e.g. https://github.com/pypa/setuptools/issues/1390).

Following a suggestion of @di in https://github.com/pypa/setuptools/issues/1390#issuecomment-432411556, I would do the following:

1. Add a `validation` module to [packaging](https://github.com/pypa/packaging/tree/master/packaging) that provides a class with a `validate()` method and an `error` list attribute (an interface that [can be easily used](https://github.com/pypa/warehouse/blob/master/warehouse/forklift/legacy.py#L771-L782) in Web frameworks like Pyramid and Django).
1. Use this module [in setuptools.dist.write_pkg_file](https://github.com/pypa/setuptools/blob/914cf24928e2c95d6d084bb36b6fe22cade4b8e2/setuptools/dist.py#L56-L81) to validate all incoming data [against their specification](https://packaging.python.org/specifications/core-metadata/). Setuptools, specifically, would then abort with an `InvalidMetadataError` if the specs are not met (instead of continuing silently generating a broken PKG-INFO file, as today).

Does that sound like something that makes sense?

Should I proceed and open a PR for a `validation` module?

**Comment by bittner** [comment]
I'm not sure if you have started already as there is no PR yet, but if it helps you can take over parts of my code in [PR #732](https://github.com/pypa/setuptools/pull/1562/files#diff-732a083cd8d83795a5237920fb3b9b38R59) (e.g. the `Metadata` class) -- if that looks somewhat the direction you want to go.

I'm curious about what the interface and and usage pattern will look like, to know whether the [implementation in](https://github.com/pypa/setuptools/pull/1562/files#diff-0f33d7d69d9f143736a252a75373261bR60) `write_pkg_file`will have to look a lot different than in [PR #732](https://github.com/pypa/setuptools/pull/732).

**Comment by bittner** [comment]
Any progress with this issue? Setuptools' [issue #1390](https://github.com/pypa/setuptools/issues/1390#issuecomment-432411556) is waiting for this to be implemented first.

**Comment by bittner** [comment]
Any progress on this? I had hoped I could help fix this easily and quickly. Anything I can do to help get up to speed?

Reference to my original PR: https://github.com/pypa/setuptools/pull/1562

**Comment by bittner** [comment]
@di Any progress with metadata validation?

**Comment by brainwane** [comment]
We discussed this at the packaging mini-summit in May and I've created https://github.com/pypa/packaging-problems/issues/264 as a tracking issue covering the various TODOs necessary to plumb this through the parts of the toolchain.

**Comment by bhrutledge** [comment]
Here's @di's work thus far, in case other folks are interested in picking it up:

https://github.com/di/packaging/tree/metadata-validation
Diff: https://github.com/pypa/packaging/compare/master...di:metadata-validation

**Comment by brainwane** [comment]
https://github.com/pypa/packaging/compare/master...crwilcox:metadata-validation @crwilcox also took a stab at this, I believe?

At this point I am guessing that both @di and @crwilcox have stepped away from this task; it would be very helpful for the pip resolver work (see https://github.com/pypa/packaging-problems/issues/264 ) over the next few months.

**Comment by bittner** [comment]
As a feedback to our community: It pays off to encourage people to _modify_ their contribution instead of bluntly dismissing it as "broken" or stating "my idea is the better one", in a certain sense. It's all about people. We Pythonistas should know better. We should _do_ better.

`</offtopic>`

**Comment by merwok** [comment]
It’s not clear what you’re referring to: I don’t find any message saying `broken` or `better` in this thread.

**Comment by di** [comment]
Wanted to post a bit of an update where I'm at with this since it's been a while, and answer some questions. *TL;DR* this issue is now unblocked and I'm going to continue working my branch.

**Where should metadata validation live?**
This project is definitely the right place for metadata validation. Metadata is defined in multiple PEPs, and this project is the implementation and standardization of these PEPs, for reuse across all packaging projects.

**Where should the implementation come from?**
While other projects might currently offer some degree of metadata validation, right now, the only one place where the "canonical" validation is happening is on PyPI. Ideally, we should take from the implementation there as much as possible since a) it is already completely defined b) we want to be able to swap in any replacement there without a ton of work.

**What's was the current delay about?**
Besides just life in general slowing me down, there's one issue in particular that has been blocking me finishing this. The branch that I was working on that was posted above is nearly complete, except for one metadata field: `Classifiers`.

**What's the problem with the `Classifiers` field?**
Right now, classifiers live in PyPI's database, and the only way to get the list of valid classifiers is by making an HTTP request to PyPI... every time, since the valid list could possibly be changed from one moment to the next. This would definitely be unacceptable.

**Why don't we just do it later?**
Slightly more acceptable would be shipping this without having support for classifiers, which would work, but is really just pushing the work onto our future selves. Additionally, this flaw would be pretty annoying for users, it would be hard to explain to them why validation works for everything except one field, and it probably wouldn't get fixed quickly.

**What's the ideal solution?**
Ideally, we would pull the storage of classifiers out of PyPI and into an external package. This would required a bit of a re-architecting of how PyPI handles classifiers, but I think it's worth it: in addition to unblocking this issue, it also puts the classifiers in a place where they can be reused, and makes it _much_ easier for folks to request new trove classifiers -- it would just be a PR.

**What's the update?**
Today, I've done just that, releasing the [`trove-classifiers`](https://github.com/pypa/trove-classifiers) package and making the necessary changes to PyPI to use it instead in https://github.com/pypa/warehouse/pull/7582. As a result, this issue is now unblocked and I'm going to continue working on my branch. 🎉 

I'd appreciate thoughts & insights from folks that are interested in contributing. I'd especially appreciate a review on the upcoming PR to this repo, since I'm not familiar with the needs of all the tools that may want to use this feature, and want to be able to provide an API that can ideally be used by all of them.

**Comment by brainwane** [comment]
Thank you for this @di!

**Comment by westurner** [comment]
Are there other package servers that don't currently validate metadata? E.g. devpi, a directory served over HTTP

Is there a valid use case for custom local metadata; such as local trove classifiers?

Is there a PEP that says that metadata MUST validate?

Should there be an environment variable and/or a commandline switch for skipping / customizing metadata validation? E.g. `_SKIP_METADATA_VALIDATION="classifiers,version"`?

**Comment by pradyunsg** [comment]
@di Would you have any ETA for the PR, in terms of an approximate quantum of time (like, a few days, around 5 weeks, a couple of months, or a few hours 🙂)?

**Comment by di** [comment]
@pradyunsg My only blocker at this point is finding enough hours in the day to finish this. I'll try to make another push on this this week and give an update at the end of the week.

**Comment by pradyunsg** [comment]
Ah, awesome, thanks!

**Comment by brainwane** [comment]
@di is this still on your personal roadmap or should it be available for someone else to take over?

**Comment by di** [comment]
Both, really. I think @brettcannon was talking about working on this soon. There is also a draft of the API in #332.

**Comment by brettcannon** [comment]
Yeah, I've started thinking about it as PEP 621 and PEP 643 makes it more than just a validation problem but also managing various input and output formats as well as maintaining data consistency for the metadata overall (i.e. `dynamic`).

**Comment by bhrutledge** [comment]
This came up in https://github.com/pypa/twine/pull/833#issuecomment-977850496. Are there any updates?

That also reminded me of https://github.com/pypa/twine/issues/739, which drifted out of the scope of Twine, but remains open because of some of the suggestions starting at https://github.com/pypa/twine/issues/739#issuecomment-796463664. I wonder if any of that is relevant for this issue.

**Comment by uranusjr** [comment]
I think this mainly needs someone to actually do the bulk of the work. That’s how most recent additions happen for this repository.

**Comment by brettcannon** [comment]
I didn't push it any farther due to perceived apathy about the idea and https://pypi.org/project/pep621/ coming into existence.

It's one of those things where it's a question of whether this is low-level enough to be in this project or in a separate one due to needing to keep dependencies low (i.e. attrs or pydantic could help with that but I don't see either getting pulled in as a dependency of this project due to vendoring concerns).

**Comment by brettcannon** [comment]
And to be clear, the perceived apathy came from https://github.com/pypa/packaging/issues/383 where I was trying to come up with an API for metadata objects where the validation would occur.

If people start to show interest again then we can restart both conversations and start driving towards implementing all of this.

**Comment by abravalheri** [comment]
Sorry, I am afraid not 😓.

I suppose such extension would need to be very specific for the `pyporject.toml` use case... First it needs to parse TOML and then apply the different JSON Schemas provided for different parts of the data-structure. Not sure if this workflow can be easily integrated into existing extensions...

**Comment by di** [comment]
For anyone following this issue, #518 was recently merged which adds a Metadata API, which this can now build upon.

**Comment by di** [comment]
Aaaaand removed in https://github.com/pypa/packaging/pull/603. Larger meta issue here: https://github.com/pypa/packaging/issues/570.

**Comment by brettcannon** [comment]
Closed by #686
