### ISSUE TITLE
Document comparing different version number classes is not supported

### ISSUE THREAD

**Issue by guifre** [pypa/packaging#216]
Using the latest version, the following statement returns true, but it should instead return false.

version.parse('1.0.2t') <= version.parse('0.9.8r')

**Comment by brettcannon** [comment]
I'm not sure if those versions are supported as the [spec in PEP 440](https://www.python.org/dev/peps/pep-0440/#public-version-identifiers) that `packaging.version` implements wouldn't allow the `r` or `t` parts of either as having semantic meaning.

Maybe the code should raise `NotImplemented` when trying to do a comparison of versions with [local  version identifiers](https://www.python.org/dev/peps/pep-0440/#local-version-identifiers)?

**Comment by pradyunsg** [comment]
```py
>>> version.parse('0.9.8r')
<Version('0.9.8.post0')>
>>> version.parse('1.0.2t')
<LegacyVersion('1.0.2t')>
>>> version.parse('0.9.8r')._key
(0, (0, 9, 8), Infinity, ('post', 0), Infinity, -Infinity)
>>> version.parse('1.0.2t')._key
(-1, ('00000001', '00000000', '00000002', '*t', '*final'))
```

Seems to me that we have a bug related to how we handle `rc` in `[N!]N(.N)*[{a|b|rc}N][.postN][.devN]`.

**Comment by pradyunsg** [comment]
Ah, no -- `r` is described as an alias for post: https://www.python.org/dev/peps/pep-0440/#post-release-spelling. Along with that, the number in `.postN` is optional: https://www.python.org/dev/peps/pep-0440/#implicit-post-release-number

I don't know what the fix for this is -- we could change up the keys, but that'd risk introducing more regressions meanwhile, the only situation this would show up, is if you're using just `r` at the end of the version string.

I'm in favor of calling this a won't fix, but if someone else is super inclined to try to fix this while not changing any of the other ordering promises we make, you're welcome to. :)

**Comment by brettcannon** [comment]
I agree that this is probably a "won't fix" scenario and at best returning `NotImplemented` so people don't get odd comparisons would also be a good solution.

**Comment by pradyunsg** [comment]
> at best returning `NotImplemented` so people don't get odd comparisons would also be a good solution

Could you elaborate upon this? I'm not sure I understand what you're suggesting here (just got back from 2 back-to-back exams to end exams week, so, like, sorry if it's something obvious and I'm not getting it).

**Comment by guifre** [comment]
If we are not going to support this, I agree throwing an exception and let the client handle it is a better solution, rather than returning an erroneous results that silently propagates to client code.

**Comment by brettcannon** [comment]
@pradyunsg See https://docs.python.org/3/reference/datamodel.html#the-standard-type-hierarchy. Basically if you define a custom rich comparison method you should return `NotImplemented` if you don't support the comparison some how (i.e. you can't compare between `Version` and `LegacyVersion`). This let's `type` try the inverse comparison (e.g. if `A.__lt__(B)` returns `NotImplemented then `B.__gt__(A)` is attempted).  And then if neither object can handle the the comparison then `type` will raise `TypeError` for you.

**Comment by pradyunsg** [comment]
@brettcannon Yea, we're doing `NotImplemented` for things that are not versions already.

However, for anything that's returned by `packaging.version.parse`, we have an `_key` that we compare using and the structure of the "key" is such that `LegacyVersion`s are always ordered "lower" than `Version`s -- i.e. all `Version` > `LegacyVersion`.

I'm not warm to the idea that we should change how this behaves, since, well, pip depends on this behavior directly for implementing how it orders distributions and arguably, that's a good reason to be *very* careful when making changes here.

**Comment by brettcannon** [comment]
@pradyunsg then I would argue this issue should be changed to a documentation to make it clear what comparisons we do and do not support and why we aren't necessarily triggering an exception here.

**Comment by pradyunsg** [comment]
Fair enough! Done! ^>^

**Comment by deveshks** [comment]
Hi @brettcannon 

I would like to work on this issue. 

If I understand correctly, we need to document here that comparing two versions, one belonging to `packaging.version.Version` and the other belonging to `packaging.version.LegacyVersion` is not supported, and any result obtained by such a comparison is ambiguous and should not be trusted? Or are there other subtleties we need to document as well related to the two Version number classes?

Also is this something we can add as a note/warning in https://github.com/pypa/packaging/blob/master/docs/version.rst ?

**Comment by brettcannon** [comment]
@deveshks  The key point is the one @pradyunsg made:

> LegacyVersion instances are always ordered lower than Version instances (i.e. all Version > LegacyVersion).

**Comment by deveshks** [comment]
> > LegacyVersion instances are always ordered lower than Version instances (i.e. all Version > LegacyVersion).

Okay, so we have two points then:

1. Comparing two versions, one belonging to Version and the other belonging to LegacyVersion is not supported
2. LegacyVersion instances are always ordered lower than Version instances (i.e. all Version > LegacyVersion).

For the docs, do we add both points 1 and 2, or only point 1, or only point 2? (If we add point 2, we can add examples to show the inequality too?)

**Comment by brettcannon** [comment]
We should only add one of them as both of them contradict themselves.

@pradyunsg do you have an opinion on how to document this?

**Comment by pradyunsg** [comment]
> @pradyunsg do you have an opinion on how to document this?

Just point 2 is good enough. It'd be a good idea to flag that some strings are valid PEP 440 string even if they look very similar to other versions that are not (i.e. the example from OP).

**Comment by deveshks** [comment]
Thanks for all the inputs. I have created the initial PR addressing these points in the docs
