### ISSUE TITLE
Visually separate PyPy interpreter version from name

### ISSUE THREAD

**Issue by brettcannon** [pypa/packaging#233]
The interpreter tag of `pp370` looks like (at least to me) that this is PyPy for Python 3.7.0 which isn't accurate: it's actually PyPy3 7.0. If the name was changed to `pp3_70` it would be more obvious this is about PyPy3 7.0.

@mattip would PyPy like to see this change? We would emit tags for both `pp370` and `pp3_70` for a while to keep compatibility to give a clear, easy, long transition.

**Comment by mattip** [comment]
I assume you are referring to the PEP425 python tag. It is documented as `py_version_nodot`, so IMO it should be pp3 or pp36 or pp37 (for python 3.6 and python 3.7 respectively). The current value of pp370 is indeed very confusing.

The pypy version (currently 7.2.0 or 7.2.1) is only relevant for the C-API, python compatibility should only be dictated by the `sys,version_info` numbers. The current active version of PyPy is python3.6 compatible, we will be releasing a python3.7 probably early in 2020.

The ABI tag is very different, but only needed for c-extension packages. The PEP states "Each implementation's community may decide how to best use the ABI tag.", and I think the PyPy community is zeroing in on a tag that combines the `sys.version_info[:2]` with `sys.pypy_version_info[:2]` so something like `pypy36_pp72`. I say "zeroing in" because we recently noticed problems with the way `pep425.py` produces the ABI tag on windows. For instance, the [wheels for pillow](https://pypi.org/project/Pillow/6.1.0/#files) use `Pillow-6.1.0-pp370-pp370-win32.whl` where the ABI tag is the same as the python tag. This is different from [linux wheels](https://antocuni.github.io/pypy-wheels/manylinux2010/numpy/), which use `numpy-1.17.3-pp372-pypy3_72-manylinux2010_x86_64.whl`. We have solved this [(a few hours ago, actually)](https://bitbucket.org/pypy/pypy/src/24c4196d86af1f0d75d87ae3cd9e22c3fea67510/lib-python/3/sysconfig.py#lines-453) by emitting a value for `sysconfig.get_config_var('SOABI')` on windows, like on linux.

We currently do not have a "stable API" story; wheels must be recreated for each python version of every pypy release.

**Comment by brettcannon** [comment]
@mattip you're correct this is all about PEP 425 tags.

As of right now the PyPy interpreter is determined by:

https://github.com/pypa/packaging/blob/bb80ca79069f29deb771697b8305deac54295be0/packaging/tags.py#L183-L191

and not `py_version_nodot` (that's the fallback when a more specialized approach is not available for an interpreter). This was taken directly from what pip does today. Should this be changed to be:

https://github.com/pypa/packaging/blob/bb80ca79069f29deb771697b8305deac54295be0/packaging/tags.py#L462-L467

instead/as well?

Right now the ABI is determined by the `SOABI` config value:

https://github.com/pypa/packaging/blob/bb80ca79069f29deb771697b8305deac54295be0/packaging/tags.py#L194-L200

**Comment by mattip** [comment]
+1 from me for the changes going forward. But `_generic_abi()` will always return `none` on current pypy releases on windows. What is the timeline for releasing this package as part of pip/setuptools instead of pep425.py? We intend to release a pypy with the fix to `sysconfig.get_config_var("SOABI")` soonish. How soon should "soonish" be?

**Comment by brettcannon** [comment]
@mattip For when this will land in pip, #231 has to get merged first and probably a bugfix or two need to get fixed, and then a pip developer has to pull it in which probably depends on when someone like @chrahunt gets to it. So I personally don't have a timeline and I don't think anyone else does either; it's just "when it's ready".

In regards to your "+1 for the changes going forward", is that to use `_generic_interpreter()` instead of `_pypy_interpreter()` to get the interpreter name? IOW in #231 that would mean dropping `pypy_tags()` and just using `generic_tags()` as the interpreter name is the only difference right now. And BTW I think that `SOABI` change will fix #184 will it not?

**Comment by mattip** [comment]
+1 for dropping `_pypy_interpreter` in favor of `_generic_interpreter`, and just using `generic_tags`. I commented on #184, thanks for helping us work through that.

**Comment by xavfernandez** [comment]
> How soon should "soonish" be?

If everything goes smoothly (and I see no reason it shouldn't) this will be in next pip version 20.0 which should be released in January 2020.

**Comment by brettcannon** [comment]
@mattip thanks for the feedback! I will fix #231 and drop `pypy_tags()` in favour of `generic_tags()` before it gets merged.

**Comment by mattip** [comment]
@brettcannon Thanks for making sure pypy is supported.

**Comment by brettcannon** [comment]
I've dropped the PyPy-specific code from #231 , so I'm going to go ahead and close this issue.

**Comment by ncoghlan** [comment]
We missed the stop of getting `wheel` to stop generating the custom PyPy interpreter tag: https://github.com/pypa/wheel/issues/329
