### ISSUE TITLE
Pre-release versions not included when specifying version interval

### ISSUE THREAD

**Issue by andy-maier** [pypa/packaging#315]
Please see https://github.com/pypa/pip/issues/8425 which describes the details. It has been noted that the issue likely should be reported here.

**Comment by di** [comment]
If I understand pypa/pip#8425 correctly, the perceived issue is that the following is `False` but shouldn't be:

```
>>> from packaging.version import Version
>>> from packaging.specifiers import Specifier
>>> Version('1.0.0b1') in Specifier('<1.0.0', prereleases=True)
False
```

However, this is intentional: https://github.com/pypa/packaging/blob/59e14881910bf836c43b7d319ea08ab321ccfb39/packaging/specifiers.py#L538-L544

Imagine a sequence of releases like:

    0.8.0, 0.9.0b1, 0.9.0b2, 0.9.0, 1.0.0b1, 1.0.0b2, 1.0.0

If we were just trying to order these, then you would expect '1.0.0b1' < '1.0.0'. But the operators in the specifiers are not just about ordering, but also about compatibility.

A user on 0.8.0 that wants to get the 0.x.y prereleases, but doesn't want any of the breaking changes that 1.0.0 might introduce, can do:

    pip install --pre package<1.0.0

This guarantees that if 0.9.0b1 and 0.9.0b2 are released, they get those updates, but if 1.0.0b1 and 1.0.0b2 are released, they aren't upgraded to a potentially incompatible version.

Looking at your specific examples and just considering `1.0.0b1`, there's basically two behaviors introducing your "STRANGE" results:

> * `pip install 'apispec>0.39.0,<1.0.0' --pre` - does not find a version - STRANGE

This is because '1.0.0b1' is not _compatible with_ '<1.0.0'

> * `pip install 'apispec>0.39.0,<1.0.0rc1'` - does not find a version - STRANGE

This is because you haven't used `--pre`, so pip is ignoring all prereleases. If you had specified `--pre`, this would have installed '1.0.0b6'

> * `pip install 'apispec>=1.0.0b1,<1.0.0'` - does not find a version - STRANGE

This is because '1.0.0b1' is not _compatible with_ '<1.0.0'

> * `pip install 'apispec>=1.0.0b1,<1.0.0' --pre` - does not find a version - STRANGE

This is because '1.0.0b1' is not _compatible with_ '<1.0.0'

**Comment by brettcannon** [comment]
I agree with @di that I wouldn't expect to be able to install the rc version of something that is explicitly blocked by the version specifier.

**Comment by pradyunsg** [comment]
Thanks @di for taking the time to take a closer look at this issue.

I am in agreement that the current behaviour is (1) appropriate and (2) standards compliant (see PEP 440's section on ordering/operators).

**Comment by brettcannon** [comment]
With the three of us agreeing I'm going to go ahead and close this.

Thanks for at least triggering the conversation, @andy-maier !
