### ISSUE TITLE
RTD Changelog is out of date

### ISSUE THREAD

**Issue by jwodder** [pypa/packaging#415]
[The changelog on the RTD site](https://packaging.pypa.io/en/latest/changelog.html) does not list the most recent release (20.9).

**Comment by brettcannon** [comment]
It's a weird failure since https://packaging.pypa.io/en/latest/utils.html#packaging.utils.parse_wheel_filename is there and that was a 20.9 change.

**Comment by puetzk** [comment]
Possibly because the CHANGELOG.rst has a syntax error in the 20.9 tag? Later fixed by #394

**Comment by brettcannon** [comment]
Latest on the site is still outdated: https://packaging.pypa.io/en/latest/changelog.html. But the latest doc build _isn't_: https://packaging--423.org.readthedocs.build/en/423/changelog.html.

I think it's because the RTD config needs to be updated to read from `main` instead of `master`: https://readthedocs.org/projects/packaging/versions/.

@pradyunsg @di either of you have permissions on RTD to fix this?

**Comment by brettcannon** [comment]
Maybe it's time to set up an RTD config file? https://docs.readthedocs.io/en/stable/config-file/index.html

**Comment by pradyunsg** [comment]
Looking now!

**Comment by pradyunsg** [comment]
From https://readthedocs.org/projects/packaging/builds/13622045/:

> Command git checkout --force master failed: error: pathspec 'master' did not match any file(s) known to git.

I changed the branch to `main` in the GUI settings (at https://readthedocs.org/dashboard/packaging/advanced/), and retriggered both `latest` and `stable`:

https://readthedocs.org/projects/packaging/builds/13622051/
https://readthedocs.org/projects/packaging/builds/13622049/

The changelog changes are live now.

**Comment by pradyunsg** [comment]
Thanks for the report @jwodder! ^>^

**Comment by pradyunsg** [comment]
Upstream issue, with RTD: https://github.com/readthedocs/readthedocs.org/issues/7907
