### ISSUE TITLE
ClamAV: Malware Found: hello-world-invalid-class

### ISSUE THREAD

**Issue by adamjstewart** [pypa/packaging#447]
I'm assuming that this is a false positive (although it would be good for a developer to confirm).

The following file gets flagged by ClamAV as containing malware:
https://github.com/pypa/packaging/blob/main/tests/manylinux/hello-world-invalid-class

If this is not actually malware, I wonder if there is a way to report this as a false positive to ClamAV or somehow modify the file so that it doesn't get flagged.

**Comment by brettcannon** [comment]
You can see how the file is built at https://github.com/pypa/packaging/blob/main/tests/manylinux/build.sh, but it's not malware. And how we use it can be seen in

https://github.com/pypa/packaging/blob/d59efa2141210447ae21c4d48813d720e0d1dbfd/tests/test_manylinux.py#L240-L253

IOW we don't even execute the code, so even if it was malicious (which it isn't), you would have to be the one that runs it. It's probably getting flagged because it's purposefully corrupted.

As for reporting it, I have no idea since I had not heard of ClamAV until now. 😄

**Comment by adamjstewart** [comment]
Perhaps the file could be generated only when the tests are run instead of storing it in the git repo?

**Comment by brettcannon** [comment]
That will slow down test runs and is not even necessarily feasible in order to generate all those files on the various architectures as we are not willing to require Docker to run the test suite.

**Comment by uranusjr** [comment]
One possibility would be to only store the executables that do require Docker, and generate the rest on-the-fly. `hello-world-invalid-header` is not built from Docker directly, but manually modified to contain invalid ELF header, which could be the reason ClamAV misidentifies it.
