### ISSUE TITLE
Does caching belong in `packaging` or `pip`?

### ISSUE THREAD

**Issue by jbylund** [pypa/packaging#460]
Issue to hold some higher level discussion about caching/performance and if it belongs in `packaging` in in consumers (`pip` & others).

Two prs are currently open:
#458 and
#459

**Comment by pradyunsg** [comment]
I think I agree that this belongs in pip.

The strongest reason that I can think of is that the users of this library should make the call on what they want the characteristics of the cache to be (memory usage, LRU vs LFU etc) and it is fairly trivial to cache these objects outside of this library.

What does make sense for us here though, is optimising how this library works. That isn’t what this issue is about, but improving how much memory we use for parsing things, and possibly writing a hand-crafted parser for requirements, would be ideal.

**Comment by jbylund** [comment]
Just by way of example, `factory:find_candidates` and `constructors:install_req_from_req_string` (both from pip) construct a ton of requirement objects, which currently call `pyparsing:parseString` which is expensive (everything relatively speaking).  One option would be that pip could have a wrapper class over `Requirement` which adds the caching behavior?

**Comment by pradyunsg** [comment]
Looks like we have agreement!
