### ISSUE TITLE
Incompliant SpecifierSet behavior with prerelease versions

### ISSUE THREAD

**Issue by arcivanov** [pypa/packaging#48]
Consider the following [snippet](https://github.com/pypa/packaging/blob/master/packaging/specifiers.py#L717):
```
        # We can determine if we're going to allow pre-releases by looking to
        # see if any of the underlying items supports them. If none of them do
        # and this item is a pre-release then we do not allow it and we can
        # short circuit that here.
        # Note: This means that 1.0.dev1 would not be contained in something
        #       like >=1.0.devabc however it would be in >=1.0.debabc,>0.0.dev0
        if not prereleases and item.is_prerelease:
            return False
```
The actual code does not comply with the stated purpose in the comment above.

`SpecifierSet(">=1.0.devabc,>0.0.dev0", False).contains(Version("1.0.dev1")) == False`

What should be happening is:

```
SpecifierSet(">=1.0", False).contains(Version("1.1.dev1")) == False
SpecifierSet(">=1.0", True).contains(Version("1.1.dev1")) == True
SpecifierSet(">=1.0,>0.0.dev0", False).contains(Version("1.1.dev1")) == True
SpecifierSet(">=1.0,>0.0.dev0", True).contains(Version("1.1.dev1")) == True
```

**Comment by arcivanov** [comment]
related to pypa/pip#3281

**Comment by dstufft** [comment]
Unless I'm confused (and I have a headache, so I might be!) you're overriding that logic by passing an explicit ``False`` to ``SpecifierSet()``. We only look at the underlying items if you haven't explicitly told ``SpecifierSet`` to include (or not include) prereleases.

In other words, ``SpecifierSet("ANYTHING", False)`` will *never* allow a prerelease version to match, because you've told us that you don't want them.

**Comment by dstufft** [comment]
Also ``1.0.dev1`` is < ``1.0`` so ``1.0.dev1`` can never match ``>=1.0``.

**Comment by arcivanov** [comment]
corrected the example

**Comment by arcivanov** [comment]
Here is the problem, with `prereleases=True`.

If `prereleases=True` then already we have `SpecifierSet(">=1.0", True).contains(Version("1.1.dev1")) == True`.

The purpose of `">=1.0,>0.0.dev0"` is to specify that we want prereleases without force-matching.

See http://pip.readthedocs.org/en/stable/reference/pip_install/#pre-release-versions

**Comment by dstufft** [comment]
There are three possible values for ``prereleases``, you have ``True``, ``False``, and ``None`` (default). 

* Passing ``True`` will *always* allow pre-releases (assuming they otherwise match) no matter what is contained in the specifier.
* Passing ``False`` will *never* allow pre-releases no matter is contained in the specifier.
* Passing ``None`` (or passing nothing) will conditionally allow pre-releases based on what is contained within the specifier.

**Comment by arcivanov** [comment]
Duh! Thanks, not a bug. Sorry for the noise.

**Comment by dstufft** [comment]
No problem :)
