### ISSUE TITLE
Markers do not work correctly when comparing python_full_version 3.10

### ISSUE THREAD

**Issue by mpyatishev** [pypa/packaging#492]
Environment:
```
$ python --version
Python 3.10.0+
$ pip --version
pip 21.3.1 from /home/max/work/env/lib/python3.10/site-packages/pip (python 3.10)
```

How to reproduce:
```
$ echo "charset-normalizer==2.0.9; python_full_version >= '3.5.0'" > requirements.txt
$ cat requirements.txt 
charset-normalizer==2.0.9; python_full_version >= '3.5.0'
$ pip install -r requirements.txt
Ignoring charset-normalizer: markers 'python_full_version >= "3.5.0"' don't match your environment
```

I have investigated that `operator.ge` don't compare '3.10' and '3.5.0' in a right way.

```
In [1]: import operator

In [2]: operator.ge('3.10', '3.5')
Out[2]: False

In [3]: operator.ge('3.9', '3.5')
Out[3]: True
```

**Comment by brettcannon** [comment]
This is all correct from a comparison perspective. The `operator` module is from Python's stdlib, not this project. Plus you are comparing two strings and not objects representing versions, and since `"5"` is greater than `"1"`, that's the right outcome.

What you want to do is use [`packaging.version`](https://packaging.pypa.io/en/latest/version.html):
```Python
>>> import packaging.version
>>> packaging.version.Version("3.10") > packaging.version.Version("3.5")
True
```

Otherwise you want to convert the version numbers to tuples, i.e. `(3, 10)` and `(3, 5)` and those will compare appropriately.

You also don't need `python_full_version` for `3.5.0`; you can use `python_version >= '3.5'`.

But the marker is still doing the right thing from our project's perspective:
```Python
>>> import packaging.markers
>>> marker = packaging.markers.Marker('python_full_version >= "3.5.0"')
>>> import sys
>>> sys.version_info
sys.version_info(major=3, minor=10, micro=0, releaselevel='final', serial=0)
>>> marker.evaluate()
True
```

So I can't reproduce your problem. I would double-check that `pip` is using your Python 3.10 installation (i.e. always use `python -m pip` and not the `pip` command directly).
