### ISSUE TITLE
Support editable

### ISSUE THREAD

**Issue by sontek** [pypa/packaging#64]
```
In [1]: from packaging.requirements import Requirement

In [2]: Requirement('-e git://hello/world/git#egg=Hello')
---------------------------------------------------------------------------
InvalidRequirement                        Traceback (most recent call last)
<ipython-input-2-5b0607f7b9e2> in <module>()
----> 1 Requirement('-e git://hello/world/git#egg=Hello')

/home/sontek/venvs/tox/local/lib/python2.7/site-packages/packaging/requirements.pyc in __init__(self, requirement_string)
     92             raise InvalidRequirement(
     93                 "Invalid requirement, parse error at \"{0!r}\"".format(
---> 94                     requirement_string[e.loc:e.loc + 8]))
     95 
     96         self.name = req.name

InvalidRequirement: Invalid requirement, parse error at "'-e git:/'"
```

**Comment by xavfernandez** [comment]
Hmm, `-e` is a `pip` option, so I see no reason for `packaging` to be able to parse it.

**Comment by sontek** [comment]
@xavfernandez I'm trying to utilize `packaging` inside `tox` to parse `requirements.txt`.  I guess I probably misunderstood what `packaging` was for.  Should it be able to parse `requirements.txt`?

**Comment by xavfernandez** [comment]
I would not think so as `requirements.txt` files are only specified in relation to `pip` behavior. I see them as a shortcut for `pip` invocation.

Meanwhile `packaging` currently seems aimed at providing helping functions for PEP-backed packaging features.

It currently supports [PEP440](https://www.python.org/dev/peps/pep-0440/), [PEP503](https://www.python.org/dev/peps/pep-0503/) and [PEP508](https://www.python.org/dev/peps/pep-0508/).

But since `pip` actively uses `packaging` to parse version numbers and such there is definitely an overlap.

**Comment by jmbowman** [comment]
`pip` does not have a stable API, resulting in bugs like https://github.com/nvie/pip-tools/issues/358 for other tools that try to work with requirements files.  When this happens, the pip people [suggest](https://github.com/pypa/pip/issues/3673#issuecomment-218539154) using the `packaging` API instead, but it currently doesn't support the full requirements file syntax.  Given that context, which of the following do you think is most appropriate?

* Add support for parsing `-e` requirements (and other valid requirements file syntax) to `packaging`
* Create a new library which attempts to support the full requirements file syntax, using `packaging` where possible to do so
* Keep using the pip API to parse requirements files, and accept the fact that it will always require an extremely recent pip version and can be broken at any time by a new incompatible pip release
* Give up on the idea of being able to manipulate requirements files with anything other than the pip command line

I'm open to other suggestions also.  I just took a stab at fixing the pip-tools bug I mentioned above, and the lack of support for editable requirements in `packaging` is making it more difficult than I had hoped.

**Comment by dstufft** [comment]
I'm going to close this issue, because I think that ``-e`` is a pip construct and isn't something that is broadly applicable to every single tool that wants to interact with Python packaging.

It's true that we suggest folks use ``packaging`` when they're currently reaching inside of pip, but that isn't a globally applicable suggestion to be honest. If what you're doing is well covered by one of the generic pieces in ``packaging`` then it's going to be a far better option for you, but sometimes that's not what you're doing.

In this case, the real underlying desire seems to be less about wanting to have a way to represent editables, and more about a way to parse ``requirements.txt`` files. Given that ``requirements.txt`` files are incredibly pip specific that makes this issue even less likely to be resolved in this repository.

------

Looking at the issue itself and the options presented, my thoughts are:

> Add support for parsing -e requirements (and other valid requirements file syntax) to packaging

As I said above, this is the wrong thing to go in ``packaging`` because it's incredibly pip specific.

> Create a new library which attempts to support the full requirements file syntax, using packaging where possible to do so.

This is a reasonable option, and if done correctly it'll be something that pip itself could consume in favor of it's own internal requirements file parsing. It will require a bit more effort to do it this way (particularly since it'll end up requiring duplicating options between the requirments file and the cli parsing in pip) but it'll be a lot cleaner I think.

> Keep using the pip API to parse requirements files, and accept the fact that it will always require an extremely recent pip version and can be broken at any time by a new incompatible pip release.
> Give up on the idea of being able to manipulate requirements files with anything other than the pip command line

These is the status quo, it sucks all around but it's likely to be the answer that we go with unless someone puts in the effort (which it sounds like maybe @jmbowman was trying to do here!) which I don't personally have free cycles to do at the moment.

There is another option though that's missing from the above, which is:

> Do the work to standardize the requirements parsing API within pip itself and expose that as our first officially supported API.

I don't personally like this idea as much as splitting it out into it's own library because right now it's easy to say "if you ``import pip`` that's a private API" but now this will end up mixing private and not private in the same ``pip/``` namespace. I also think it doesn't save a whole lot of work because a lot of the significant effort is going to be refactoring this so that it doesn't expose other, still internal APIs as part of it's API surface (right now it returns ``InstallRequirement`` objects, which we would want to remain internal). The primary benefit of this option is not needing to deal with setting up the infrastructure for another project, and being able to share definitions for things like ``--index-url`` (as well as being able to share defaults) between requirements.txt and the CLI.
