### ISSUE TITLE
Local version labels in version specifiers

### ISSUE THREAD

**Issue by edible-programs** [pypa/packaging#661]
```python3.10
from packaging import requirements
requirements.parse_requirement("torch>=1.13.1+cu117")
# Expected end or semicolon (after version specifier)
```

**Comment by pradyunsg** [comment]
Argh, `parse_requirement` isn't supposed to be a public function.

Beyond that, `>=1.13.1+cu117` isn't a valid version specifier per the existing language of PEP 508 and PEP 440. You can see this since this was being parsed as a `LegacySpecifier` within older versions of `packaging` (with 21.3 below).

```pycon
>>> # packaging 21.3
>>> from packaging.requirements import Requirement
>>> list(Requirement("torch>=1.13.1+cu117").specifier)
[<LegacySpecifier('>=1.13.1+cu117')>]
```

It does have reasonable semantics if you expect to have a monotonically increasing number (although it'd work better with a `.` between cu and the number).

```
>>> # packaging 21.3
>>> Requirement("torch>=1.13.1+cu117").specifier.contains(Version("1.13.1+cu117"))
True
>>> Requirement("torch>=1.13.1+cu117").specifier.contains(Version("1.13.1+cu116"))
False
>>> Requirement("torch>=1.13.1+cu117").specifier.contains(Version("1.13.1+cu118"))
True
```

It does seem like a valid version specifier and a valid usecase but, as it stands, PEP 508 and PEP 440 don't permit using local version labels in version specifiers. This works in pip and packaging 21.3 for the same reasons that the following "works":

```pycon
>>> # packaging 21.3
>>> list(Requirement("torch>=absolutelyanythinghere").specifier)
[<LegacySpecifier('>=absolutelyanythinghere')>]
```

**Comment by pradyunsg** [comment]
I've filed https://discuss.python.org/t/lets-permit-local-version-label-in-version-specifiers/22781 for this.

**Comment by pradyunsg** [comment]
We’ve settled on no for this. See the discussion above for the details.
