### ISSUE TITLE
Specifier comparison broken

### ISSUE THREAD

**Issue by toabctl** [pypa/packaging#69]
Using packaging 16.5 I try to find the lowest version from a given SpecifierSet:

```
$ python
Python 2.7.10 (default, May 24 2015, 14:46:10) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from packaging.specifiers import SpecifierSet
>>> s = SpecifierSet("!=1.2.0,!=1.3b1,<1.3,>=1.1.2")
>>> min(s)
<Specifier('!=1.2.0')>
```

I expected that the minimum version is ```1.1.2```.

**Comment by jaraco** [comment]
A Specifier isn't a version, but a specifier for versions. Resolving a 'minimum' viable version from a set of specifiers doesn't seem straightforward. Consider:

```
min(SpecifierSet(">=2.0,<1.0"))
```

or

```
min(SpecifierSet(">=2.0,!=2.0"))
```

The `min` function in Python only returns the object in a sequence that compares least, but since Specifier objects don't implement any of the comparison operators, I'm not sure what Python does to compare those objects. I would not have had the expectation you did, but would have expected an error or possibly an undefined (arbitrary) result.

Perhaps SpecifierSet could get a `calc_min_version` method or similar, to accomplish what you expect. What is your use case?

**Comment by dstufft** [comment]
A ``Specifier`` is not conceptually orderable, the only reason you get *any* value is because Python 2.x makes anything orderable, even if it makes no sense. If you had instead used Python 3.x you would have gotten an error instead:

```pycon
>>> from packaging.specifiers import SpecifierSet
>>> s = SpecifierSet("!=1.2.0,!=1.3b1,<1.3,>=1.1.2")
>>> min(s)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    min(s)
TypeError: unorderable types: Specifier() < Specifier()
```

I don't think it really makes any sense to make a ``Specifier`` orderable either tbh.

**Comment by toabctl** [comment]
Hm. Ok. Sounds right. The usecase is to get the minimum version for a given `SpecifierSet`. I need it when I try to convert the given versions to a single version for RPM packaging.
I use now:
```
from packaging.specifiers import SpecifierSet
s = SpecifierSet("!=1.2.0,!=1.3b1,<1.3,>=1.1.2")
min(map(lambda x: x.version, s))
```

Thanks for the clarification!
