### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Secrus** [pypa/packaging#718]
Please make a new release so we, humble users, can use the new metadata API.

**Comment by mtelka** [comment]
`setuptools 68.2.0` now requires [dev version of packaging](https://github.com/pypa/setuptools/blob/v68.2.0/tox.ini#L6) to use the metadata API.

**Comment by pradyunsg** [comment]
> `setuptools 68.2.0` now requires [dev version of packaging](https://github.com/pypa/setuptools/blob/v68.2.0/tox.ini?rgh-link-date=2023-09-07T22%3A05%3A40Z#L6) to use the metadata API.

To be clear, it's a test-only dependency -- it doesn't actually depend on that at runtime or for users to be able to use it.

**Comment by pradyunsg** [comment]
@brettcannon Do you have any blocking concerns regarding a new release? If not, I'll make some time to cut one over the coming few day.

**Comment by brettcannon** [comment]
@pradyunsg nope, nothing critical from my side (or a quick glance at open issues or PRs).

**Comment by Deku963** [comment]
pip install packaging
HEpl me 
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (23.1)
DEPRECATION: adns 1.4-py1 has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of adns or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063

**Comment by Secrus** [comment]
@Deku963 This is not the right issue for that. Please don't hijack it.

**Comment by pradyunsg** [comment]
@Deku963 I think that [Python Discord's #help-* channels](https://discord.gg/python), [#python on Libera.chat](https://web.libera.chat/#python) ([IRC](https://workaround.org/getting-help-on-irc/)), [python-list](https://mail.python.org/mailman/listinfo/python-list) or [python-tutor](https://mail.python.org/mailman/listinfo/tutor) mailing lists,or [StackOverflow](https://stackoverflow.com) would be better channels to get support for the issue you're facing.

**Comment by Secrus** [comment]
@pradyunsg any update on that?

**Comment by mayeut** [comment]
With pypa/pip#12300 upgrading packaging for pip 23.3, it's probably a good thing to do a release before it gets merged with an outdated packaging release.

**Comment by pradyunsg** [comment]
https://github.com/pypa/packaging/releases/tag/23.2 is up! :)
