### ISSUE TITLE
packaging 22+ break PackagingSpecifierSet with extended version

### ISSUE THREAD

**Issue by gsemet** [pypa/packaging#773]
Was working with packaging 21.3:
```
SpecifierSet(f"<0.0.1.dev1+g3cdcc", prereleases=True)
```

In all versions since 22.0, we get:
```
packaging.specifiers.InvalidSpecifier: Invalid specifier: '<0.0.1.dev1+g3cdcc'
```

For me, `0.0.1.dev1+g3cdcc` and `0.0.1.dev1` and equivalent so i do not understand why `0.0.1.dev1+g3cdcc` is refused by `SpecifierSet`

**Comment by pradyunsg** [comment]
Please see https://github.com/pypa/packaging/issues/530

**Comment by pradyunsg** [comment]
Wait, I should elaborate.

In #530, there's discussion about why invalid inputs are now rejected  by `packaging`. As for why this is invalid input, from [the version specificiation](https://packaging.python.org/en/latest/specifications/version-specifiers/#exclusive-ordered-comparison) for the operator being used:

> Local version identifiers are NOT permitted in this version specifier.

So, the new behaviour here is correct. Further, packaging 21.3 returned a `LegacySpecifier`...

```
>>> list(SpecifierSet("<0.0.1.dev1+g3cdcc"))
[<LegacySpecifier('<0.0.1.dev1+g3cdcc')>]
```

... and packaging 21.3 also raises a warning when run in development mode.

```
❯ python -X dev -c "from packaging.specifiers import SpecifierSet; SpecifierSet('<0.0.1.dev1+g3cdcc')"
/Users/pradyunsg/Developer/github/pip/.venv/lib/python3.11/site-packages/packaging/specifiers.py:255: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
```

Closing this out since the question asked has been answered, and I don't expect that we'd be changing behaviour here unless you reckon this is worth doing a standard specification update for.
