### ISSUE TITLE
`metadata.Metadata` unable to parse setuptools-generated metadata files.

### ISSUE THREAD

**Issue by fiannac** [pypa/packaging#778]
Metadata generated by setuptool may contain the currently non-standard `License-File` field described in [PEP-639](https://peps.python.org/pep-0639/) (Example: setuptools' [METADATA](https://files.pythonhosted.org/packages/55/3a/5121b58b578a598b269537e09a316ad2a94fdd561a2c6eb75cd68578cc6b/setuptools-69.0.3-py3-none-any.whl.metadata)).

`from_raw` and `from_email` class methods of `packaging.metadata.Metadata`  in `packaging==23.2` perform a strict check of all fields within the METADATA file, raising if they encounter an unrecognised field, and are therfore usuable for any metadata generated by setuptools that specify the `license-file` field.

You can reproduce the problem by running:

```python
Metadata.from_email("""Metadata-Version: 2.1
Name: name
Version: 0.0.1
License-File: license""")
```

**Comment by dstufft** [comment]
This should be considered by design I think. Non standard Metadata may never happen, it may be wildly different than what the standard says, etc. The default mode is to be strict.

If you need to be lenient then you'll need to either pass `validate=False` to the `from_email` or `from_raw` methods (which shifts validation from being done up front to being done on demand) or construct your own `RawMetadata` and pass that into `from_raw`.

**Comment by brettcannon** [comment]
. @dstufft is right that this is by design. `RawMetadata` exists to allow for just parsing out keys w/o validating anything. And you can turn complete validation off for `Metadata` so you only validate on access of an attribute, letting invalid metadata that doesn't affect you pass by silently.
